package com.androidx.briefness.homepage.module;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/example/generate/LoginModule.proto

public final class LoginModule {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_LoginParam_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_LoginParam_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_LoginResult_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_LoginResult_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n&com/example/generate/LoginModule.proto" +
                        "\".\n\nLoginParam\022\016\n\006mobile\030\001 \001(\t\022\020\n\010passwo" +
                        "rd\030\002 \001(\t\"\200\001\n\013LoginResult\022\014\n\004code\030\001 \001(\021\022\013" +
                        "\n\003msg\030\002 \001(\t\022\014\n\004sign\030\003 \001(\t\022\013\n\003puk\030\004 \001(\t\022\r" +
                        "\n\005token\030\005 \001(\t\022\n\n\002id\030\006 \001(\t\022\020\n\010username\030\007 " +
                        "\001(\t\022\016\n\006mobile\030\010 \001(\tB\rB\013LoginModuleb\006prot" +
                        "o3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_LoginParam_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_LoginParam_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_LoginParam_descriptor,
                new String[]{"Mobile", "Password",});
        internal_static_LoginResult_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_LoginResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_LoginResult_descriptor,
                new String[]{"Code", "Msg", "Sign", "Puk", "Token", "Id", "Username", "Mobile",});
    }

    private LoginModule() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface LoginParamOrBuilder extends
            // @@protoc_insertion_point(interface_extends:LoginParam)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string mobile = 1;</code>
         *
         * @return The mobile.
         */
        String getMobile();

        /**
         * <code>string mobile = 1;</code>
         *
         * @return The bytes for mobile.
         */
        com.google.protobuf.ByteString
        getMobileBytes();

        /**
         * <code>string password = 2;</code>
         *
         * @return The password.
         */
        String getPassword();

        /**
         * <code>string password = 2;</code>
         *
         * @return The bytes for password.
         */
        com.google.protobuf.ByteString
        getPasswordBytes();
    }

    public interface LoginResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:LoginResult)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>sint32 code = 1;</code>
         *
         * @return The code.
         */
        int getCode();

        /**
         * <code>string msg = 2;</code>
         *
         * @return The msg.
         */
        String getMsg();

        /**
         * <code>string msg = 2;</code>
         *
         * @return The bytes for msg.
         */
        com.google.protobuf.ByteString
        getMsgBytes();

        /**
         * <code>string sign = 3;</code>
         *
         * @return The sign.
         */
        String getSign();

        /**
         * <code>string sign = 3;</code>
         *
         * @return The bytes for sign.
         */
        com.google.protobuf.ByteString
        getSignBytes();

        /**
         * <code>string puk = 4;</code>
         *
         * @return The puk.
         */
        String getPuk();

        /**
         * <code>string puk = 4;</code>
         *
         * @return The bytes for puk.
         */
        com.google.protobuf.ByteString
        getPukBytes();

        /**
         * <code>string token = 5;</code>
         *
         * @return The token.
         */
        String getToken();

        /**
         * <code>string token = 5;</code>
         *
         * @return The bytes for token.
         */
        com.google.protobuf.ByteString
        getTokenBytes();

        /**
         * <code>string id = 6;</code>
         *
         * @return The id.
         */
        String getId();

        /**
         * <code>string id = 6;</code>
         *
         * @return The bytes for id.
         */
        com.google.protobuf.ByteString
        getIdBytes();

        /**
         * <code>string username = 7;</code>
         *
         * @return The username.
         */
        String getUsername();

        /**
         * <code>string username = 7;</code>
         *
         * @return The bytes for username.
         */
        com.google.protobuf.ByteString
        getUsernameBytes();

        /**
         * <code>string mobile = 8;</code>
         *
         * @return The mobile.
         */
        String getMobile();

        /**
         * <code>string mobile = 8;</code>
         *
         * @return The bytes for mobile.
         */
        com.google.protobuf.ByteString
        getMobileBytes();
    }

    /**
     * Protobuf type {@code LoginParam}
     */
    public static final class LoginParam extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:LoginParam)
            LoginParamOrBuilder {
        public static final int MOBILE_FIELD_NUMBER = 1;
        public static final int PASSWORD_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:LoginParam)
        private static final LoginParam DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<LoginParam>
                PARSER = new com.google.protobuf.AbstractParser<LoginParam>() {
            @Override
            public LoginParam parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new LoginParam(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new LoginParam();
        }

        private volatile Object mobile_;
        private volatile Object password_;
        private byte memoizedIsInitialized = -1;

        // Use LoginParam.newBuilder() to construct.
        private LoginParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private LoginParam() {
            mobile_ = "";
            password_ = "";
        }

        private LoginParam(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            mobile_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            password_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return LoginModule.internal_static_LoginParam_descriptor;
        }

        public static LoginParam parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static LoginParam parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static LoginParam parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static LoginParam parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static LoginParam parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static LoginParam parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static LoginParam parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static LoginParam parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static LoginParam parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static LoginParam parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static LoginParam parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static LoginParam parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(LoginParam prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static LoginParam getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<LoginParam> parser() {
            return PARSER;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new LoginParam();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return LoginModule.internal_static_LoginParam_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            LoginParam.class, Builder.class);
        }

        /**
         * <code>string mobile = 1;</code>
         *
         * @return The mobile.
         */
        @Override
        public String getMobile() {
            Object ref = mobile_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                mobile_ = s;
                return s;
            }
        }

        /**
         * <code>string mobile = 1;</code>
         *
         * @return The bytes for mobile.
         */
        @Override
        public com.google.protobuf.ByteString
        getMobileBytes() {
            Object ref = mobile_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                mobile_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string password = 2;</code>
         *
         * @return The password.
         */
        @Override
        public String getPassword() {
            Object ref = password_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                password_ = s;
                return s;
            }
        }

        /**
         * <code>string password = 2;</code>
         *
         * @return The bytes for password.
         */
        @Override
        public com.google.protobuf.ByteString
        getPasswordBytes() {
            Object ref = password_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                password_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobile_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mobile_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobile_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mobile_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof LoginParam)) {
                return super.equals(obj);
            }
            LoginParam other = (LoginParam) obj;

            if (!getMobile()
                    .equals(other.getMobile())) return false;
            if (!getPassword()
                    .equals(other.getPassword())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MOBILE_FIELD_NUMBER;
            hash = (53 * hash) + getMobile().hashCode();
            hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
            hash = (53 * hash) + getPassword().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<LoginParam> getParserForType() {
            return PARSER;
        }

        @Override
        public LoginParam getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code LoginParam}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:LoginParam)
                LoginParamOrBuilder {
            private Object mobile_ = "";
            private Object password_ = "";

            // Construct using LoginModule.LoginParam.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return LoginModule.internal_static_LoginParam_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return LoginModule.internal_static_LoginParam_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                LoginParam.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                mobile_ = "";

                password_ = "";

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return LoginModule.internal_static_LoginParam_descriptor;
            }

            @Override
            public LoginParam getDefaultInstanceForType() {
                return LoginParam.getDefaultInstance();
            }

            @Override
            public LoginParam build() {
                LoginParam result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public LoginParam buildPartial() {
                LoginParam result = new LoginParam(this);
                result.mobile_ = mobile_;
                result.password_ = password_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof LoginParam) {
                    return mergeFrom((LoginParam) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(LoginParam other) {
                if (other == LoginParam.getDefaultInstance()) return this;
                if (!other.getMobile().isEmpty()) {
                    mobile_ = other.mobile_;
                    onChanged();
                }
                if (!other.getPassword().isEmpty()) {
                    password_ = other.password_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                LoginParam parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (LoginParam) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string mobile = 1;</code>
             *
             * @return The mobile.
             */
            public String getMobile() {
                Object ref = mobile_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    mobile_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string mobile = 1;</code>
             *
             * @param value The mobile to set.
             * @return This builder for chaining.
             */
            public Builder setMobile(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                mobile_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string mobile = 1;</code>
             *
             * @return The bytes for mobile.
             */
            public com.google.protobuf.ByteString
            getMobileBytes() {
                Object ref = mobile_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    mobile_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string mobile = 1;</code>
             *
             * @param value The bytes for mobile to set.
             * @return This builder for chaining.
             */
            public Builder setMobileBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                mobile_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string mobile = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMobile() {

                mobile_ = getDefaultInstance().getMobile();
                onChanged();
                return this;
            }

            /**
             * <code>string password = 2;</code>
             *
             * @return The password.
             */
            public String getPassword() {
                Object ref = password_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    password_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string password = 2;</code>
             *
             * @param value The password to set.
             * @return This builder for chaining.
             */
            public Builder setPassword(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string password = 2;</code>
             *
             * @return The bytes for password.
             */
            public com.google.protobuf.ByteString
            getPasswordBytes() {
                Object ref = password_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    password_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string password = 2;</code>
             *
             * @param value The bytes for password to set.
             * @return This builder for chaining.
             */
            public Builder setPasswordBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string password = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPassword() {

                password_ = getDefaultInstance().getPassword();
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:LoginParam)
        }

    }

    /**
     * Protobuf type {@code LoginResult}
     */
    public static final class LoginResult extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:LoginResult)
            LoginResultOrBuilder {
        public static final int CODE_FIELD_NUMBER = 1;
        public static final int MSG_FIELD_NUMBER = 2;
        public static final int SIGN_FIELD_NUMBER = 3;
        public static final int PUK_FIELD_NUMBER = 4;
        public static final int TOKEN_FIELD_NUMBER = 5;
        public static final int ID_FIELD_NUMBER = 6;
        public static final int USERNAME_FIELD_NUMBER = 7;
        public static final int MOBILE_FIELD_NUMBER = 8;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:LoginResult)
        private static final LoginResult DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<LoginResult>
                PARSER = new com.google.protobuf.AbstractParser<LoginResult>() {
            @Override
            public LoginResult parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new LoginResult(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new LoginResult();
        }

        private int code_;
        private volatile Object msg_;
        private volatile Object sign_;
        private volatile Object puk_;
        private volatile Object token_;
        private volatile Object id_;
        private volatile Object username_;
        private volatile Object mobile_;
        private byte memoizedIsInitialized = -1;

        // Use LoginResult.newBuilder() to construct.
        private LoginResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private LoginResult() {
            msg_ = "";
            sign_ = "";
            puk_ = "";
            token_ = "";
            id_ = "";
            username_ = "";
            mobile_ = "";
        }

        private LoginResult(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            code_ = input.readSInt32();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            msg_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            sign_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            puk_ = s;
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();

                            token_ = s;
                            break;
                        }
                        case 50: {
                            String s = input.readStringRequireUtf8();

                            id_ = s;
                            break;
                        }
                        case 58: {
                            String s = input.readStringRequireUtf8();

                            username_ = s;
                            break;
                        }
                        case 66: {
                            String s = input.readStringRequireUtf8();

                            mobile_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return LoginModule.internal_static_LoginResult_descriptor;
        }

        public static LoginResult parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static LoginResult parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static LoginResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static LoginResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static LoginResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static LoginResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static LoginResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static LoginResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static LoginResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static LoginResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static LoginResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static LoginResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(LoginResult prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static LoginResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<LoginResult> parser() {
            return PARSER;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new LoginResult();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return LoginModule.internal_static_LoginResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            LoginResult.class, Builder.class);
        }

        /**
         * <code>sint32 code = 1;</code>
         *
         * @return The code.
         */
        @Override
        public int getCode() {
            return code_;
        }

        /**
         * <code>string msg = 2;</code>
         *
         * @return The msg.
         */
        @Override
        public String getMsg() {
            Object ref = msg_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            }
        }

        /**
         * <code>string msg = 2;</code>
         *
         * @return The bytes for msg.
         */
        @Override
        public com.google.protobuf.ByteString
        getMsgBytes() {
            Object ref = msg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string sign = 3;</code>
         *
         * @return The sign.
         */
        @Override
        public String getSign() {
            Object ref = sign_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                sign_ = s;
                return s;
            }
        }

        /**
         * <code>string sign = 3;</code>
         *
         * @return The bytes for sign.
         */
        @Override
        public com.google.protobuf.ByteString
        getSignBytes() {
            Object ref = sign_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                sign_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string puk = 4;</code>
         *
         * @return The puk.
         */
        @Override
        public String getPuk() {
            Object ref = puk_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                puk_ = s;
                return s;
            }
        }

        /**
         * <code>string puk = 4;</code>
         *
         * @return The bytes for puk.
         */
        @Override
        public com.google.protobuf.ByteString
        getPukBytes() {
            Object ref = puk_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                puk_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string token = 5;</code>
         *
         * @return The token.
         */
        @Override
        public String getToken() {
            Object ref = token_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                token_ = s;
                return s;
            }
        }

        /**
         * <code>string token = 5;</code>
         *
         * @return The bytes for token.
         */
        @Override
        public com.google.protobuf.ByteString
        getTokenBytes() {
            Object ref = token_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                token_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string id = 6;</code>
         *
         * @return The id.
         */
        @Override
        public String getId() {
            Object ref = id_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                id_ = s;
                return s;
            }
        }

        /**
         * <code>string id = 6;</code>
         *
         * @return The bytes for id.
         */
        @Override
        public com.google.protobuf.ByteString
        getIdBytes() {
            Object ref = id_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string username = 7;</code>
         *
         * @return The username.
         */
        @Override
        public String getUsername() {
            Object ref = username_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                username_ = s;
                return s;
            }
        }

        /**
         * <code>string username = 7;</code>
         *
         * @return The bytes for username.
         */
        @Override
        public com.google.protobuf.ByteString
        getUsernameBytes() {
            Object ref = username_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                username_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string mobile = 8;</code>
         *
         * @return The mobile.
         */
        @Override
        public String getMobile() {
            Object ref = mobile_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                mobile_ = s;
                return s;
            }
        }

        /**
         * <code>string mobile = 8;</code>
         *
         * @return The bytes for mobile.
         */
        @Override
        public com.google.protobuf.ByteString
        getMobileBytes() {
            Object ref = mobile_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                mobile_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (code_ != 0) {
                output.writeSInt32(1, code_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sign_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sign_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(puk_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, puk_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, token_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, id_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, username_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobile_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, mobile_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (code_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, code_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sign_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sign_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(puk_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, puk_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, token_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, id_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, username_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobile_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, mobile_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof LoginResult)) {
                return super.equals(obj);
            }
            LoginResult other = (LoginResult) obj;

            if (getCode()
                    != other.getCode()) return false;
            if (!getMsg()
                    .equals(other.getMsg())) return false;
            if (!getSign()
                    .equals(other.getSign())) return false;
            if (!getPuk()
                    .equals(other.getPuk())) return false;
            if (!getToken()
                    .equals(other.getToken())) return false;
            if (!getId()
                    .equals(other.getId())) return false;
            if (!getUsername()
                    .equals(other.getUsername())) return false;
            if (!getMobile()
                    .equals(other.getMobile())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode();
            hash = (37 * hash) + MSG_FIELD_NUMBER;
            hash = (53 * hash) + getMsg().hashCode();
            hash = (37 * hash) + SIGN_FIELD_NUMBER;
            hash = (53 * hash) + getSign().hashCode();
            hash = (37 * hash) + PUK_FIELD_NUMBER;
            hash = (53 * hash) + getPuk().hashCode();
            hash = (37 * hash) + TOKEN_FIELD_NUMBER;
            hash = (53 * hash) + getToken().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId().hashCode();
            hash = (37 * hash) + USERNAME_FIELD_NUMBER;
            hash = (53 * hash) + getUsername().hashCode();
            hash = (37 * hash) + MOBILE_FIELD_NUMBER;
            hash = (53 * hash) + getMobile().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<LoginResult> getParserForType() {
            return PARSER;
        }

        @Override
        public LoginResult getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code LoginResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:LoginResult)
                LoginResultOrBuilder {
            private int code_;
            private Object msg_ = "";
            private Object sign_ = "";
            private Object puk_ = "";
            private Object token_ = "";
            private Object id_ = "";
            private Object username_ = "";
            private Object mobile_ = "";

            // Construct using LoginModule.LoginResult.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return LoginModule.internal_static_LoginResult_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return LoginModule.internal_static_LoginResult_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                LoginResult.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                code_ = 0;

                msg_ = "";

                sign_ = "";

                puk_ = "";

                token_ = "";

                id_ = "";

                username_ = "";

                mobile_ = "";

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return LoginModule.internal_static_LoginResult_descriptor;
            }

            @Override
            public LoginResult getDefaultInstanceForType() {
                return LoginResult.getDefaultInstance();
            }

            @Override
            public LoginResult build() {
                LoginResult result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public LoginResult buildPartial() {
                LoginResult result = new LoginResult(this);
                result.code_ = code_;
                result.msg_ = msg_;
                result.sign_ = sign_;
                result.puk_ = puk_;
                result.token_ = token_;
                result.id_ = id_;
                result.username_ = username_;
                result.mobile_ = mobile_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof LoginResult) {
                    return mergeFrom((LoginResult) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(LoginResult other) {
                if (other == LoginResult.getDefaultInstance()) return this;
                if (other.getCode() != 0) {
                    setCode(other.getCode());
                }
                if (!other.getMsg().isEmpty()) {
                    msg_ = other.msg_;
                    onChanged();
                }
                if (!other.getSign().isEmpty()) {
                    sign_ = other.sign_;
                    onChanged();
                }
                if (!other.getPuk().isEmpty()) {
                    puk_ = other.puk_;
                    onChanged();
                }
                if (!other.getToken().isEmpty()) {
                    token_ = other.token_;
                    onChanged();
                }
                if (!other.getId().isEmpty()) {
                    id_ = other.id_;
                    onChanged();
                }
                if (!other.getUsername().isEmpty()) {
                    username_ = other.username_;
                    onChanged();
                }
                if (!other.getMobile().isEmpty()) {
                    mobile_ = other.mobile_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                LoginResult parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (LoginResult) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>sint32 code = 1;</code>
             *
             * @return The code.
             */
            @Override
            public int getCode() {
                return code_;
            }

            /**
             * <code>sint32 code = 1;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(int value) {

                code_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>sint32 code = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {

                code_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 2;</code>
             *
             * @return The msg.
             */
            public String getMsg() {
                Object ref = msg_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string msg = 2;</code>
             *
             * @param value The msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsg(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 2;</code>
             *
             * @return The bytes for msg.
             */
            public com.google.protobuf.ByteString
            getMsgBytes() {
                Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string msg = 2;</code>
             *
             * @param value The bytes for msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMsg() {

                msg_ = getDefaultInstance().getMsg();
                onChanged();
                return this;
            }

            /**
             * <code>string sign = 3;</code>
             *
             * @return The sign.
             */
            public String getSign() {
                Object ref = sign_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    sign_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string sign = 3;</code>
             *
             * @param value The sign to set.
             * @return This builder for chaining.
             */
            public Builder setSign(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                sign_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string sign = 3;</code>
             *
             * @return The bytes for sign.
             */
            public com.google.protobuf.ByteString
            getSignBytes() {
                Object ref = sign_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    sign_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string sign = 3;</code>
             *
             * @param value The bytes for sign to set.
             * @return This builder for chaining.
             */
            public Builder setSignBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                sign_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string sign = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSign() {

                sign_ = getDefaultInstance().getSign();
                onChanged();
                return this;
            }

            /**
             * <code>string puk = 4;</code>
             *
             * @return The puk.
             */
            public String getPuk() {
                Object ref = puk_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    puk_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string puk = 4;</code>
             *
             * @param value The puk to set.
             * @return This builder for chaining.
             */
            public Builder setPuk(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                puk_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string puk = 4;</code>
             *
             * @return The bytes for puk.
             */
            public com.google.protobuf.ByteString
            getPukBytes() {
                Object ref = puk_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    puk_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string puk = 4;</code>
             *
             * @param value The bytes for puk to set.
             * @return This builder for chaining.
             */
            public Builder setPukBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                puk_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string puk = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPuk() {

                puk_ = getDefaultInstance().getPuk();
                onChanged();
                return this;
            }

            /**
             * <code>string token = 5;</code>
             *
             * @return The token.
             */
            public String getToken() {
                Object ref = token_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    token_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string token = 5;</code>
             *
             * @param value The token to set.
             * @return This builder for chaining.
             */
            public Builder setToken(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                token_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string token = 5;</code>
             *
             * @return The bytes for token.
             */
            public com.google.protobuf.ByteString
            getTokenBytes() {
                Object ref = token_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    token_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string token = 5;</code>
             *
             * @param value The bytes for token to set.
             * @return This builder for chaining.
             */
            public Builder setTokenBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                token_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string token = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearToken() {

                token_ = getDefaultInstance().getToken();
                onChanged();
                return this;
            }

            /**
             * <code>string id = 6;</code>
             *
             * @return The id.
             */
            public String getId() {
                Object ref = id_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    id_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string id = 6;</code>
             *
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string id = 6;</code>
             *
             * @return The bytes for id.
             */
            public com.google.protobuf.ByteString
            getIdBytes() {
                Object ref = id_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string id = 6;</code>
             *
             * @param value The bytes for id to set.
             * @return This builder for chaining.
             */
            public Builder setIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string id = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearId() {

                id_ = getDefaultInstance().getId();
                onChanged();
                return this;
            }

            /**
             * <code>string username = 7;</code>
             *
             * @return The username.
             */
            public String getUsername() {
                Object ref = username_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    username_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string username = 7;</code>
             *
             * @param value The username to set.
             * @return This builder for chaining.
             */
            public Builder setUsername(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                username_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string username = 7;</code>
             *
             * @return The bytes for username.
             */
            public com.google.protobuf.ByteString
            getUsernameBytes() {
                Object ref = username_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    username_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string username = 7;</code>
             *
             * @param value The bytes for username to set.
             * @return This builder for chaining.
             */
            public Builder setUsernameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                username_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string username = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUsername() {

                username_ = getDefaultInstance().getUsername();
                onChanged();
                return this;
            }

            /**
             * <code>string mobile = 8;</code>
             *
             * @return The mobile.
             */
            public String getMobile() {
                Object ref = mobile_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    mobile_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string mobile = 8;</code>
             *
             * @param value The mobile to set.
             * @return This builder for chaining.
             */
            public Builder setMobile(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                mobile_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string mobile = 8;</code>
             *
             * @return The bytes for mobile.
             */
            public com.google.protobuf.ByteString
            getMobileBytes() {
                Object ref = mobile_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    mobile_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string mobile = 8;</code>
             *
             * @param value The bytes for mobile to set.
             * @return This builder for chaining.
             */
            public Builder setMobileBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                mobile_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string mobile = 8;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMobile() {

                mobile_ = getDefaultInstance().getMobile();
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:LoginResult)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
