package com.androidx.briefness.homepage.module;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.module.protobuf/ReceiveModule.proto

public final class ReceiveModule {
    private ReceiveModule() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface ReceiveResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ReceiveResult)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>string msg = 1;</code>
         *
         * @return The msg.
         */
        String getMsg();

        /**
         * <code>string msg = 1;</code>
         *
         * @return The bytes for msg.
         */
    com.google.protobuf.ByteString
    getMsgBytes();

        /**
         * <code>string sign = 2;</code>
     * @return The sign.
         */
        String getSign();

        /**
         * <code>string sign = 2;</code>
     * @return The bytes for sign.
     */
    com.google.protobuf.ByteString
    getSignBytes();

        /**
         * <code>string puk = 3;</code>
     * @return The puk.
         */
        String getPuk();

        /**
         * <code>string puk = 3;</code>
     * @return The bytes for puk.
     */
    com.google.protobuf.ByteString
    getPukBytes();

        /**
         * <code>string token = 4;</code>
     * @return The token.
         */
        String getToken();

        /**
         * <code>string token = 4;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
    getTokenBytes();

        /**
         * <code>string data = 5;</code>
         *
         * @return The data.
         */
        String getData();

        /**
         * <code>string data = 5;</code>
         *
         * @return The bytes for data.
         */
        com.google.protobuf.ByteString
        getDataBytes();

        /**
         * <code>int32 code = 6;</code>
         *
         * @return The code.
         */
        int getCode();
    }

    /**
     * Protobuf type {@code ReceiveResult}
     */
    public static final class ReceiveResult extends
            com.google.protobuf.GeneratedMessageLite<
                    ReceiveResult, ReceiveResult.Builder> implements
            // @@protoc_insertion_point(message_implements:ReceiveResult)
            ReceiveResultOrBuilder {
        public static final int MSG_FIELD_NUMBER = 1;
        public static final int SIGN_FIELD_NUMBER = 2;
        public static final int PUK_FIELD_NUMBER = 3;
        public static final int TOKEN_FIELD_NUMBER = 4;
        public static final int DATA_FIELD_NUMBER = 5;
        public static final int CODE_FIELD_NUMBER = 6;
        // @@protoc_insertion_point(class_scope:ReceiveResult)
        private static final ReceiveResult DEFAULT_INSTANCE;
        private static volatile com.google.protobuf.Parser<ReceiveResult> PARSER;

        static {
            ReceiveResult defaultInstance = new ReceiveResult();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    ReceiveResult.class, defaultInstance);
        }

        private String msg_;
        private String sign_;
        private String puk_;
        private String token_;
        private String data_;
        private int code_;

        private ReceiveResult() {
            msg_ = "";
            sign_ = "";
            puk_ = "";
            token_ = "";
            data_ = "";
        }

        public static ReceiveResult parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static ReceiveResult parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static ReceiveResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static ReceiveResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static ReceiveResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static ReceiveResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static ReceiveResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static ReceiveResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static ReceiveResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }

        public static ReceiveResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static ReceiveResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static ReceiveResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }

        public static Builder newBuilder(ReceiveResult prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        public static ReceiveResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ReceiveResult> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }

        /**
         * <code>string msg = 1;</code>
         * @return The msg.
         */
        @Override
        public String getMsg() {
            return msg_;
        }

        /**
         * <code>string msg = 1;</code>
         * @param value The msg to set.
         */
        private void setMsg(
                String value) {
            value.getClass();

            msg_ = value;
        }

        /**
         * <code>string msg = 1;</code>
         * @return The bytes for msg.
         */
        @Override
        public com.google.protobuf.ByteString
        getMsgBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(msg_);
        }

        /**
         * <code>string msg = 1;</code>
         * @param value The bytes for msg to set.
         */
        private void setMsgBytes(
                com.google.protobuf.ByteString value) {
            checkByteStringIsUtf8(value);
            msg_ = value.toStringUtf8();

        }

        /**
         * <code>string msg = 1;</code>
         */
        private void clearMsg() {

            msg_ = getDefaultInstance().getMsg();
        }

        /**
         * <code>string sign = 2;</code>
         * @return The sign.
         */
        @Override
        public String getSign() {
            return sign_;
        }

        /**
         * <code>string sign = 2;</code>
         * @param value The sign to set.
         */
        private void setSign(
                String value) {
            value.getClass();

            sign_ = value;
        }

        /**
         * <code>string sign = 2;</code>
         * @return The bytes for sign.
         */
        @Override
        public com.google.protobuf.ByteString
        getSignBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(sign_);
        }

        /**
         * <code>string sign = 2;</code>
         * @param value The bytes for sign to set.
         */
        private void setSignBytes(
                com.google.protobuf.ByteString value) {
            checkByteStringIsUtf8(value);
            sign_ = value.toStringUtf8();

        }

        /**
         * <code>string sign = 2;</code>
         */
        private void clearSign() {

            sign_ = getDefaultInstance().getSign();
        }

        /**
         * <code>string puk = 3;</code>
         * @return The puk.
         */
        @Override
        public String getPuk() {
            return puk_;
        }

        /**
         * <code>string puk = 3;</code>
         * @param value The puk to set.
         */
        private void setPuk(
                String value) {
            value.getClass();

            puk_ = value;
        }

        /**
         * <code>string puk = 3;</code>
         * @return The bytes for puk.
         */
        @Override
        public com.google.protobuf.ByteString
        getPukBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(puk_);
        }

        /**
         * <code>string puk = 3;</code>
         * @param value The bytes for puk to set.
         */
        private void setPukBytes(
                com.google.protobuf.ByteString value) {
            checkByteStringIsUtf8(value);
            puk_ = value.toStringUtf8();

        }

        /**
         * <code>string puk = 3;</code>
         */
        private void clearPuk() {

            puk_ = getDefaultInstance().getPuk();
        }

        /**
         * <code>string token = 4;</code>
         * @return The token.
         */
        @Override
        public String getToken() {
            return token_;
        }

        /**
         * <code>string token = 4;</code>
         * @param value The token to set.
         */
        private void setToken(
                String value) {
            value.getClass();

            token_ = value;
        }

        /**
         * <code>string token = 4;</code>
         * @return The bytes for token.
         */
        @Override
        public com.google.protobuf.ByteString
        getTokenBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(token_);
        }

        /**
         * <code>string token = 4;</code>
         * @param value The bytes for token to set.
         */
        private void setTokenBytes(
                com.google.protobuf.ByteString value) {
            checkByteStringIsUtf8(value);
            token_ = value.toStringUtf8();

        }

        /**
         * <code>string token = 4;</code>
         */
        private void clearToken() {

            token_ = getDefaultInstance().getToken();
        }

        /**
         * <code>string data = 5;</code>
         * @return The data.
         */
        @Override
        public String getData() {
            return data_;
        }

        /**
         * <code>string data = 5;</code>
         * @param value The data to set.
         */
        private void setData(
                String value) {
            value.getClass();

            data_ = value;
        }

        /**
         * <code>string data = 5;</code>
         * @return The bytes for data.
         */
        @Override
        public com.google.protobuf.ByteString
        getDataBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(data_);
        }

        /**
         * <code>string data = 5;</code>
         * @param value The bytes for data to set.
         */
        private void setDataBytes(
                com.google.protobuf.ByteString value) {
            checkByteStringIsUtf8(value);
            data_ = value.toStringUtf8();

        }

        /**
         * <code>string data = 5;</code>
         */
        private void clearData() {

            data_ = getDefaultInstance().getData();
        }

        /**
         * <code>int32 code = 6;</code>
         * @return The code.
         */
        @Override
        public int getCode() {
            return code_;
        }

        /**
         * <code>int32 code = 6;</code>
         * @param value The code to set.
         */
        private void setCode(int value) {

            code_ = value;
        }

        /**
         * <code>int32 code = 6;</code>
         */
        private void clearCode() {

            code_ = 0;
        }

        @Override
        @SuppressWarnings({"unchecked", "fallthrough"})
        protected final Object dynamicMethod(
                MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new ReceiveResult();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    Object[] objects = new Object[]{
                            "msg_",
                            "sign_",
                            "puk_",
                            "token_",
                            "data_",
                            "code_",
                    };
                    String info =
                            "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                                    "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0004";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<ReceiveResult> parser = PARSER;
                    if (parser == null) {
                        synchronized (ReceiveResult.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<ReceiveResult>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }

        /**
         * Protobuf type {@code ReceiveResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        ReceiveResult, Builder> implements
                // @@protoc_insertion_point(builder_implements:ReceiveResult)
                ReceiveResultOrBuilder {
            // Construct using ReceiveModule.ReceiveResult.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>string msg = 1;</code>
             * @return The msg.
             */
            @Override
            public String getMsg() {
                return instance.getMsg();
            }

            /**
             * <code>string msg = 1;</code>
             * @param value The msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsg(
                    String value) {
                copyOnWrite();
                instance.setMsg(value);
                return this;
            }

            /**
             * <code>string msg = 1;</code>
             * @return The bytes for msg.
             */
            @Override
            public com.google.protobuf.ByteString
            getMsgBytes() {
                return instance.getMsgBytes();
            }

            /**
             * <code>string msg = 1;</code>
             * @param value The bytes for msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setMsgBytes(value);
                return this;
            }

            /**
             * <code>string msg = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearMsg() {
                copyOnWrite();
                instance.clearMsg();
                return this;
            }

            /**
             * <code>string sign = 2;</code>
             * @return The sign.
             */
            @Override
            public String getSign() {
                return instance.getSign();
            }

            /**
             * <code>string sign = 2;</code>
             * @param value The sign to set.
             * @return This builder for chaining.
             */
            public Builder setSign(
                    String value) {
                copyOnWrite();
                instance.setSign(value);
                return this;
            }

            /**
             * <code>string sign = 2;</code>
             *
             * @return The bytes for sign.
             */
            @Override
            public com.google.protobuf.ByteString
            getSignBytes() {
                return instance.getSignBytes();
            }

            /**
             * <code>string sign = 2;</code>
             *
             * @param value The bytes for sign to set.
             * @return This builder for chaining.
             */
            public Builder setSignBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setSignBytes(value);
                return this;
            }

            /**
             * <code>string sign = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSign() {
                copyOnWrite();
                instance.clearSign();
                return this;
            }

            /**
             * <code>string puk = 3;</code>
             *
             * @return The puk.
             */
            @Override
            public String getPuk() {
                return instance.getPuk();
            }

            /**
             * <code>string puk = 3;</code>
             * @param value The puk to set.
             * @return This builder for chaining.
             */
            public Builder setPuk(
                    String value) {
                copyOnWrite();
                instance.setPuk(value);
                return this;
            }

            /**
             * <code>string puk = 3;</code>
             *
             * @return The bytes for puk.
             */
            @Override
            public com.google.protobuf.ByteString
            getPukBytes() {
                return instance.getPukBytes();
            }

            /**
             * <code>string puk = 3;</code>
             *
             * @param value The bytes for puk to set.
             * @return This builder for chaining.
             */
            public Builder setPukBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setPukBytes(value);
                return this;
            }

            /**
             * <code>string puk = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPuk() {
                copyOnWrite();
                instance.clearPuk();
                return this;
            }

            /**
             * <code>string token = 4;</code>
             *
             * @return The token.
             */
            @Override
            public String getToken() {
                return instance.getToken();
            }

            /**
             * <code>string token = 4;</code>
             * @param value The token to set.
             * @return This builder for chaining.
             */
            public Builder setToken(
                    String value) {
                copyOnWrite();
                instance.setToken(value);
                return this;
            }

            /**
             * <code>string token = 4;</code>
             *
             * @return The bytes for token.
             */
            @Override
            public com.google.protobuf.ByteString
            getTokenBytes() {
                return instance.getTokenBytes();
            }

            /**
             * <code>string token = 4;</code>
             *
             * @param value The bytes for token to set.
             * @return This builder for chaining.
             */
            public Builder setTokenBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setTokenBytes(value);
                return this;
            }

            /**
             * <code>string token = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearToken() {
                copyOnWrite();
                instance.clearToken();
                return this;
            }

            /**
             * <code>string data = 5;</code>
             *
             * @return The data.
             */
            @Override
            public String getData() {
                return instance.getData();
            }

            /**
             * <code>string data = 5;</code>
             *
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(
                    String value) {
                copyOnWrite();
                instance.setData(value);
                return this;
            }

            /**
             * <code>string data = 5;</code>
             *
             * @return The bytes for data.
             */
            @Override
            public com.google.protobuf.ByteString
            getDataBytes() {
                return instance.getDataBytes();
            }

            /**
             * <code>string data = 5;</code>
             *
             * @param value The bytes for data to set.
             * @return This builder for chaining.
             */
            public Builder setDataBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setDataBytes(value);
                return this;
            }

            /**
             * <code>string data = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearData() {
                copyOnWrite();
                instance.clearData();
                return this;
            }

            /**
             * <code>int32 code = 6;</code>
             *
             * @return The code.
             */
            @Override
            public int getCode() {
                return instance.getCode();
            }

            /**
             * <code>int32 code = 6;</code>
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(int value) {
                copyOnWrite();
                instance.setCode(value);
                return this;
            }

            /**
             * <code>int32 code = 6;</code>
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                copyOnWrite();
                instance.clearCode();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:ReceiveResult)
        }
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
