package com.module.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.module.protobuf/Message.proto

public final class MessageModule {
  private MessageModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RequestOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Request)
          com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       * 请求状态
       * </pre>
       *
       * <code>sint32 type = 1;</code>
       *
       * @return The type.
       */
      int getType();

      /**
       * <pre>
       * 发送数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       *
       * @return The data.
       */
      com.google.protobuf.ByteString getData();
  }

    public interface ResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Response)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <pre>
         *响应状态
         * </pre>
         *
         * <code>sint32 code = 1;</code>
         * @return The code.
         */
        int getCode();

        /**
         * <pre>
         *响应信息
         * </pre>
         *
         * <code>string msg = 2;</code>
         * @return The msg.
         */
        String getMsg();

        /**
         * <pre>
         *响应信息
         * </pre>
         *
         * <code>string msg = 2;</code>
         * @return The bytes for msg.
         */
        com.google.protobuf.ByteString
        getMsgBytes();

        /**
         * <pre>
         *接收数据
         * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
         */
        com.google.protobuf.ByteString getData();
    }

    /**
     * <pre>
     * 请求结构体
     * </pre>
     * <p>
     * Protobuf type {@code Request}
     */
    public static final class Request extends
            com.google.protobuf.GeneratedMessageLite<
                    Request, Request.Builder> implements
            // @@protoc_insertion_point(message_implements:Request)
            RequestOrBuilder {
        private Request() {
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;

        /**
         * <pre>
         *请求状态
         * </pre>
         *
         * <code>sint32 type = 1;</code>
         * @return The type.
         */
        @Override
        public int getType() {
            return type_;
        }

        private static volatile com.google.protobuf.Parser<Request> PARSER;

        static {
            Request defaultInstance = new Request();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    Request.class, defaultInstance);
        }

        public static final int DATA_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString data_;

        /**
         * <pre>
         *发送数据
         * </pre>
     *
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static Request parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Request parseFrom(
        com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Request parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }

        public static Request parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }

    public static Request parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Request parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }

    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }

        public static Builder newBuilder(Request prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        public static com.google.protobuf.Parser<Request> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }

        /**
         * <pre>
         * 请求状态
         * </pre>
         *
         * <code>sint32 type = 1;</code>
         *
         * @param value The type to set.
         */
        private void setType(int value) {

            type_ = value;
        }

        /**
         * <pre>
         * 请求状态
         * </pre>
         *
         * <code>sint32 type = 1;</code>
         */
        private void clearType() {

            type_ = 0;
        }

        /**
         * <pre>
         * 发送数据
         * </pre>
         *
         * <code>bytes data = 2;</code>
         *
         * @param value The data to set.
         */
        private void setData(com.google.protobuf.ByteString value) {
            value.getClass();

            data_ = value;
        }


        // @@protoc_insertion_point(class_scope:Request)
        private static final Request DEFAULT_INSTANCE;

        /**
         * <pre>
         * 发送数据
         * </pre>
         *
         * <code>bytes data = 2;</code>
         */
        private void clearData() {

            data_ = getDefaultInstance().getData();
        }

        public static Request getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Override
        @SuppressWarnings({"unchecked", "fallthrough"})
        protected final Object dynamicMethod(
                MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new Request();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    Object[] objects = new Object[]{
                            "type_",
                            "data_",
                    };
                    String info =
                            "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000f\u0002\n" +
                                    "";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<Request> parser = PARSER;
                    if (parser == null) {
                        synchronized (Request.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<Request>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }

        /**
         * <pre>
         * 请求结构体
         * </pre>
         * <p>
         * Protobuf type {@code Request}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        Request, Builder> implements
                // @@protoc_insertion_point(builder_implements:Request)
                RequestOrBuilder {
            // Construct using MessageModule.Request.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *请求状态
       * </pre>
       *
       * <code>sint32 type = 1;</code>
       * @return The type.
       */
      @Override
      public int getType() {
        return instance.getType();
      }

            /**
             * <pre>
             *请求状态
             * </pre>
             *
             * <code>sint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        copyOnWrite();
          instance.setType(value);
          return this;
      }

            /**
             * <pre>
       *请求状态
       * </pre>
       *
       * <code>sint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
          return this;
      }

      /**
       * <pre>
       *发送数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }

            /**
             * <pre>
             *发送数据
             * </pre>
             *
             * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
          instance.setData(value);
          return this;
      }

            /**
             * <pre>
       *发送数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearData() {
                copyOnWrite();
                instance.clearData();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Request)
        }
    }

    /**
     * <pre>
     * 响应结构体
     * </pre>
     * <p>
     * Protobuf type {@code Response}
     */
    public static final class Response extends
            com.google.protobuf.GeneratedMessageLite<
                    Response, Response.Builder> implements
            // @@protoc_insertion_point(message_implements:Response)
            ResponseOrBuilder {
        private Response() {
            msg_ = "";
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        public static final int CODE_FIELD_NUMBER = 1;
        private int code_;

        /**
         * <pre>
         * 响应状态
         * </pre>
         *
         * <code>sint32 code = 1;</code>
         *
         * @return The code.
         */
        @Override
        public int getCode() {
            return code_;
        }

        private static volatile com.google.protobuf.Parser<Response> PARSER;

        static {
            Response defaultInstance = new Response();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    Response.class, defaultInstance);
        }

        public static final int MSG_FIELD_NUMBER = 2;

    private String msg_;

    public static Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

        public static Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

        public static Response parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static Response parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static final int DATA_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString data_;

        /**
         * <pre>
         * 接收数据
         * </pre>
         *
         * <code>bytes data = 3;</code>
         *
         * @return The data.
         */
        @Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        public static Response parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Response parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }

    public static Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Response parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static Response parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Response parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

        public static Response parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }

        public static Builder newBuilder(Response prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        public static com.google.protobuf.Parser<Response> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }

        /**
         * <pre>
         * 响应状态
         * </pre>
         *
         * <code>sint32 code = 1;</code>
         *
         * @param value The code to set.
         */
        private void setCode(int value) {

            code_ = value;
        }

        /**
         * <pre>
         * 响应状态
         * </pre>
         *
         * <code>sint32 code = 1;</code>
         */
        private void clearCode() {

            code_ = 0;
        }

        /**
         * <pre>
         * 响应信息
         * </pre>
         *
         * <code>string msg = 2;</code>
         *
         * @return The msg.
         */
        @Override
        public String getMsg() {
            return msg_;
        }

        /**
         * <pre>
         * 响应信息
         * </pre>
         *
         * <code>string msg = 2;</code>
         *
         * @param value The msg to set.
         */
        private void setMsg(
                String value) {
            value.getClass();

            msg_ = value;
        }

        /**
         * <pre>
         * 响应信息
         * </pre>
         *
         * <code>string msg = 2;</code>
         *
         * @return The bytes for msg.
         */
        @Override
        public com.google.protobuf.ByteString
        getMsgBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(msg_);
        }

        /**
         * <pre>
         * 响应信息
         * </pre>
         *
         * <code>string msg = 2;</code>
         *
         * @param value The bytes for msg to set.
         */
        private void setMsgBytes(
                com.google.protobuf.ByteString value) {
            checkByteStringIsUtf8(value);
            msg_ = value.toStringUtf8();

        }

        /**
         * <pre>
         * 响应信息
         * </pre>
         *
         * <code>string msg = 2;</code>
         */
        private void clearMsg() {

            msg_ = getDefaultInstance().getMsg();
        }

        /**
         * <pre>
         * 接收数据
         * </pre>
         *
         * <code>bytes data = 3;</code>
         *
         * @param value The data to set.
         */
        private void setData(com.google.protobuf.ByteString value) {
            value.getClass();

            data_ = value;
        }


        // @@protoc_insertion_point(class_scope:Response)
        private static final Response DEFAULT_INSTANCE;

        /**
         * <pre>
         * 接收数据
         * </pre>
         *
         * <code>bytes data = 3;</code>
         */
        private void clearData() {

            data_ = getDefaultInstance().getData();
        }

        public static Response getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Override
        @SuppressWarnings({"unchecked", "fallthrough"})
        protected final Object dynamicMethod(
                MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new Response();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    Object[] objects = new Object[]{
                            "code_",
                            "msg_",
                            "data_",
                    };
                    String info =
                            "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000f\u0002\u0208" +
                                    "\u0003\n";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<Response> parser = PARSER;
                    if (parser == null) {
                        synchronized (Response.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<Response>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }

        /**
         * <pre>
         * 响应结构体
         * </pre>
         * <p>
         * Protobuf type {@code Response}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        Response, Builder> implements
                // @@protoc_insertion_point(builder_implements:Response)
                ResponseOrBuilder {
            // Construct using MessageModule.Response.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <pre>
             *响应状态
             * </pre>
             *
             * <code>sint32 code = 1;</code>
             * @return The code.
             */
            @Override
            public int getCode() {
                return instance.getCode();
            }

            /**
             * <pre>
             * 响应状态
             * </pre>
             *
             * <code>sint32 code = 1;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(int value) {
                copyOnWrite();
                instance.setCode(value);
                return this;
            }

            /**
             * <pre>
             *响应状态
             * </pre>
             *
             * <code>sint32 code = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                copyOnWrite();
                instance.clearCode();
                return this;
            }

            /**
             * <pre>
             *响应信息
             * </pre>
             *
             * <code>string msg = 2;</code>
             * @return The msg.
             */
            @Override
            public String getMsg() {
                return instance.getMsg();
            }

            /**
             * <pre>
             * 响应信息
             * </pre>
             *
             * <code>string msg = 2;</code>
             *
             * @param value The msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsg(
                    String value) {
                copyOnWrite();
                instance.setMsg(value);
                return this;
            }

            /**
             * <pre>
             * 响应信息
             * </pre>
             *
             * <code>string msg = 2;</code>
             *
             * @return The bytes for msg.
             */
            @Override
            public com.google.protobuf.ByteString
            getMsgBytes() {
                return instance.getMsgBytes();
            }

            /**
             * <pre>
             *响应信息
             * </pre>
             *
             * <code>string msg = 2;</code>
             * @param value The bytes for msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setMsgBytes(value);
                return this;
            }

            /**
             * <pre>
             *响应信息
             * </pre>
             *
             * <code>string msg = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearMsg() {
                copyOnWrite();
                instance.clearMsg();
                return this;
            }

            /**
             * <pre>
             *接收数据
             * </pre>
             *
             * <code>bytes data = 3;</code>
             * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <pre>
       *接收数据
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }

            /**
             * <pre>
             *接收数据
             * </pre>
             *
             * <code>bytes data = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearData() {
                copyOnWrite();
                instance.clearData();
                return this;
            }

      // @@protoc_insertion_point(builder_scope:Response)
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
