package com.module.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.module.protobuf/Msg.proto

public final class MsgModule {
  private MsgModule() {
  }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface MsgRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:MsgRequest)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <pre>
         * 请求码
         * </pre>
         *
         * <code>sint32 code = 1;</code>
         *
         * @return The code.
         */
        int getCode();

        /**
         * <pre>
         *用户ID
         * </pre>
         *
         * <code>string user_id = 2;</code>
         * @return The userId.
         */
        String getUserId();

        /**
         * <pre>
         * 用户ID
         * </pre>
         *
         * <code>string user_id = 2;</code>
         *
         * @return The bytes for userId.
         */
        com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     *数据信息
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

        /**
         * <pre>
         *发送时间
         * </pre>
         *
         * <code>string send_time = 4;</code>
         * @return The sendTime.
         */
        String getSendTime();

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>string send_time = 4;</code>
         *
         * @return The bytes for sendTime.
         */
        com.google.protobuf.ByteString
        getSendTimeBytes();
    }

    /**
     * <pre>
     * 请求结构体
     * </pre>
     * <p>
     * Protobuf type {@code MsgRequest}
     */
    public static final class MsgRequest extends
            com.google.protobuf.GeneratedMessageLite<
                    MsgRequest, MsgRequest.Builder> implements
            // @@protoc_insertion_point(message_implements:MsgRequest)
            MsgRequestOrBuilder {
        private MsgRequest() {
            userId_ = "";
            data_ = com.google.protobuf.ByteString.EMPTY;
            sendTime_ = "";
        }

        public static final int CODE_FIELD_NUMBER = 1;
        private int code_;

        /**
         * <pre>
         * 请求码
         * </pre>
         *
         * <code>sint32 code = 1;</code>
         *
         * @return The code.
         */
        @Override
        public int getCode() {
            return code_;
        }

        public static final int USER_ID_FIELD_NUMBER = 2;
        public static final int SEND_TIME_FIELD_NUMBER = 4;
        private static volatile com.google.protobuf.Parser<MsgRequest> PARSER;

        static {
            MsgRequest defaultInstance = new MsgRequest();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    MsgRequest.class, defaultInstance);
        }

        private String userId_;
        private String sendTime_;

        public static MsgRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static MsgRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

        public static MsgRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static final int DATA_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString data_;

        /**
         * <pre>
         * 数据信息
         * </pre>
         *
         * <code>bytes data = 3;</code>
         *
         * @return The data.
         */
        @Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        public static MsgRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static MsgRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
        }

        public static MsgRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static MsgRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }

        public static MsgRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static MsgRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

        public static MsgRequest parseDelimitedFrom(
                java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static MsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
        }

        public static MsgRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }

        public static Builder newBuilder(MsgRequest prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        public static com.google.protobuf.Parser<MsgRequest> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }

        /**
         * <pre>
         * 请求码
         * </pre>
         *
         * <code>sint32 code = 1;</code>
         *
         * @param value The code to set.
         */
        private void setCode(int value) {

            code_ = value;
        }

        /**
         * <pre>
         * 请求码
         * </pre>
         *
         * <code>sint32 code = 1;</code>
         */
        private void clearCode() {

            code_ = 0;
        }

        /**
         * <pre>
         * 用户ID
         * </pre>
         *
         * <code>string user_id = 2;</code>
         *
         * @return The userId.
         */
        @Override
        public String getUserId() {
            return userId_;
        }

        /**
         * <pre>
         * 用户ID
         * </pre>
         *
         * <code>string user_id = 2;</code>
         *
         * @param value The userId to set.
         */
        private void setUserId(
                String value) {
            value.getClass();

            userId_ = value;
        }

        /**
         * <pre>
         * 用户ID
         * </pre>
         *
         * <code>string user_id = 2;</code>
         *
         * @return The bytes for userId.
         */
        @Override
        public com.google.protobuf.ByteString
        getUserIdBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(userId_);
        }

        /**
         * <pre>
         * 用户ID
         * </pre>
         *
         * <code>string user_id = 2;</code>
         *
         * @param value The bytes for userId to set.
         */
        private void setUserIdBytes(
                com.google.protobuf.ByteString value) {
            checkByteStringIsUtf8(value);
            userId_ = value.toStringUtf8();

        }

        /**
         * <pre>
         * 用户ID
         * </pre>
         *
         * <code>string user_id = 2;</code>
         */
        private void clearUserId() {

            userId_ = getDefaultInstance().getUserId();
        }

        /**
         * <pre>
         * 数据信息
         * </pre>
         *
         * <code>bytes data = 3;</code>
         *
         * @param value The data to set.
         */
        private void setData(com.google.protobuf.ByteString value) {
            value.getClass();

            data_ = value;
        }

        /**
         * <pre>
         * 数据信息
         * </pre>
         *
         * <code>bytes data = 3;</code>
         */
        private void clearData() {

            data_ = getDefaultInstance().getData();
        }

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>string send_time = 4;</code>
         *
         * @return The sendTime.
         */
        @Override
        public String getSendTime() {
            return sendTime_;
        }

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>string send_time = 4;</code>
         *
         * @param value The sendTime to set.
         */
        private void setSendTime(
                String value) {
            value.getClass();

            sendTime_ = value;
        }

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>string send_time = 4;</code>
         *
         * @return The bytes for sendTime.
         */
        @Override
        public com.google.protobuf.ByteString
        getSendTimeBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(sendTime_);
        }

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>string send_time = 4;</code>
         *
         * @param value The bytes for sendTime to set.
         */
        private void setSendTimeBytes(
                com.google.protobuf.ByteString value) {
            checkByteStringIsUtf8(value);
            sendTime_ = value.toStringUtf8();

        }


        // @@protoc_insertion_point(class_scope:MsgRequest)
        private static final MsgRequest DEFAULT_INSTANCE;

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>string send_time = 4;</code>
         */
        private void clearSendTime() {

            sendTime_ = getDefaultInstance().getSendTime();
        }

        public static MsgRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Override
        @SuppressWarnings({"unchecked", "fallthrough"})
        protected final Object dynamicMethod(
                MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new MsgRequest();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    Object[] objects = new Object[]{
                            "code_",
                            "userId_",
                            "data_",
                            "sendTime_",
                    };
                    String info =
                            "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u000f\u0002\u0208" +
                                    "\u0003\n\u0004\u0208";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<MsgRequest> parser = PARSER;
                    if (parser == null) {
                        synchronized (MsgRequest.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<MsgRequest>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }

        /**
         * <pre>
         * 请求结构体
         * </pre>
         * <p>
         * Protobuf type {@code MsgRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        MsgRequest, Builder> implements
                // @@protoc_insertion_point(builder_implements:MsgRequest)
        MsgRequestOrBuilder {
      // Construct using MsgModule.MsgRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


            /**
             * <pre>
             *请求码
             * </pre>
             *
             * <code>sint32 code = 1;</code>
             * @return The code.
             */
            @Override
            public int getCode() {
                return instance.getCode();
            }

            /**
       * <pre>
       *请求码
       * </pre>
             *
             * <code>sint32 code = 1;</code>
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(int value) {
                copyOnWrite();
                instance.setCode(value);
        return this;
      }
      /**
       * <pre>
       *请求码
       * </pre>
       *
       * <code>sint32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
          copyOnWrite();
          instance.clearCode();
          return this;
      }

            /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>string user_id = 2;</code>
             * @return The userId.
             */
            @Override
            public String getUserId() {
                return instance.getUserId();
            }

            /**
             * <pre>
             *用户ID
             * </pre>
             *
             * <code>string user_id = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
             */
            public Builder setUserId(
                    String value) {
                copyOnWrite();
                instance.setUserId(value);
        return this;
      }

      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>string user_id = 2;</code>
       * @return The bytes for userId.
       */
      @Override
      public com.google.protobuf.ByteString
      getUserIdBytes() {
        return instance.getUserIdBytes();
      }

      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>string user_id = 2;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>string user_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }

      /**
       * <pre>
       *数据信息
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
          return instance.getData();
      }

            /**
             * <pre>
             *数据信息
             * </pre>
       *
       * <code>bytes data = 3;</code>
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setData(value);
                return this;
      }
      /**
       * <pre>
       *数据信息
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
          copyOnWrite();
          instance.clearData();
          return this;
      }

            /**
             * <pre>
             * 发送时间
             * </pre>
             *
             * <code>string send_time = 4;</code>
             *
             * @return The sendTime.
             */
            @Override
            public String getSendTime() {
                return instance.getSendTime();
            }

            /**
             * <pre>
             * 发送时间
             * </pre>
             *
             * <code>string send_time = 4;</code>
             *
             * @param value The sendTime to set.
             * @return This builder for chaining.
             */
            public Builder setSendTime(
                    String value) {
                copyOnWrite();
                instance.setSendTime(value);
                return this;
            }

            /**
             * <pre>
             * 发送时间
             * </pre>
             *
             * <code>string send_time = 4;</code>
             *
             * @return The bytes for sendTime.
             */
            @Override
            public com.google.protobuf.ByteString
            getSendTimeBytes() {
                return instance.getSendTimeBytes();
            }

            /**
             * <pre>
             *发送时间
             * </pre>
             *
             * <code>string send_time = 4;</code>
             * @param value The bytes for sendTime to set.
             * @return This builder for chaining.
             */
            public Builder setSendTimeBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setSendTimeBytes(value);
                return this;
            }

            /**
             * <pre>
             *发送时间
             * </pre>
             *
             * <code>string send_time = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearSendTime() {
                copyOnWrite();
                instance.clearSendTime();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:MsgRequest)
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
